import type {
  ArtifactValues,
  CapabilityManifest,
  CreativeArtifact,
  InstrumentId,
  StudioProject,
} from "./contracts";
import { assertValidArtifactOntology } from "./artifact-ontology";
import { createSeedComposition } from "../meant/composition-core";

const values = (overrides: Partial<ArtifactValues>): ArtifactValues => ({
  warmth: 50,
  contrast: 50,
  spacing: 50,
  focalStrength: 50,
  softness: 50,
  surfaceDepth: 50,
  cornerRadius: 50,
  typeScale: 50,
  accentStrength: 50,
  saturation: 50,
  cropScale: 50,
  ...overrides,
});

export const seedArtifacts: CreativeArtifact[] = [
  {
    id: "artifact-web",
    kind: "web",
    name: "Launch page",
    format: "Responsive web",
    version: 7,
    values: values({
      warmth: 62,
      contrast: 64,
      spacing: 54,
      focalStrength: 68,
      softness: 70,
      surfaceDepth: 56,
      cornerRadius: 72,
      typeScale: 58,
      accentStrength: 78,
      saturation: 58,
    }),
    nodes: [
      {
        id: "web-frame",
        name: "Launch page",
        kind: "composition",
        purpose: "The complete responsive storefront",
        role: "page",
        capabilities: ["warmth", "contrast", "spacing", "softness", "surfaceDepth", "cornerRadius", "typeScale", "saturation"],
      },
      {
        id: "web-header",
        name: "Header",
        kind: "group",
        purpose: "Brand and storefront navigation",
        role: "header",
        parentId: "web-frame",
        capabilities: ["contrast", "spacing", "typeScale"],
      },
      {
        id: "web-wordmark",
        name: "Bobalicious wordmark",
        kind: "text",
        purpose: "Primary brand signature",
        role: "brand mark",
        parentId: "web-header",
        capabilities: ["contrast", "focalStrength", "typeScale", "spacing"],
      },
      {
        id: "web-navigation",
        name: "Navigation",
        kind: "group",
        purpose: "Storefront destinations",
        role: "navigation",
        parentId: "web-header",
        capabilities: ["contrast", "spacing", "typeScale"],
      },
      {
        id: "web-nav-menu",
        name: "Menu link",
        kind: "text",
        purpose: "Opens the drink menu",
        role: "navigation label",
        parentId: "web-navigation",
        capabilities: ["contrast", "focalStrength", "typeScale"],
      },
      {
        id: "web-nav-locations",
        name: "Locations link",
        kind: "text",
        purpose: "Helps people find a shop",
        role: "navigation label",
        parentId: "web-navigation",
        capabilities: ["contrast", "focalStrength", "typeScale"],
      },
      {
        id: "web-nav-story",
        name: "Our story link",
        kind: "text",
        purpose: "Introduces the Bobalicious brand",
        role: "navigation label",
        parentId: "web-navigation",
        capabilities: ["contrast", "focalStrength", "typeScale"],
      },
      {
        id: "web-hero",
        name: "Hero composition",
        kind: "group",
        purpose: "The primary storefront story",
        role: "hero region",
        parentId: "web-frame",
        capabilities: [
          "warmth",
          "contrast",
          "spacing",
          "focalStrength",
          "softness",
          "typeScale",
        ],
      },
      {
        id: "web-copy",
        name: "Hero copy",
        kind: "group",
        purpose: "Message hierarchy and actions",
        role: "copy group",
        parentId: "web-hero",
        capabilities: ["contrast", "spacing", "focalStrength", "typeScale"],
      },
      {
        id: "web-eyebrow",
        name: "Freshness eyebrow",
        kind: "text",
        purpose: "Sets the upbeat product promise",
        role: "eyebrow",
        parentId: "web-copy",
        capabilities: ["contrast", "spacing", "focalStrength", "typeScale", "accentStrength"],
      },
      {
        id: "web-headline",
        name: "Hero headline",
        kind: "text",
        purpose: "The main campaign message",
        role: "headline",
        parentId: "web-copy",
        capabilities: ["contrast", "spacing", "focalStrength", "typeScale"],
      },
      {
        id: "web-supporting-copy",
        name: "Supporting copy",
        kind: "text",
        purpose: "Explains the drink experience",
        role: "body copy",
        parentId: "web-copy",
        capabilities: ["contrast", "spacing", "focalStrength", "typeScale"],
      },
      {
        id: "web-actions",
        name: "Order actions",
        kind: "group",
        purpose: "Primary and secondary ordering choices",
        role: "action group",
        parentId: "web-copy",
        capabilities: ["contrast", "spacing", "cornerRadius", "accentStrength"],
      },
      {
        id: "web-primary-action",
        name: "Order a favorite",
        kind: "action",
        purpose: "Primary ordering action",
        role: "primary button",
        parentId: "web-actions",
        capabilities: ["contrast", "spacing", "cornerRadius", "accentStrength", "typeScale", "focalStrength"],
      },
      {
        id: "web-secondary-action",
        name: "Build your own",
        kind: "action",
        purpose: "Secondary customization action",
        role: "secondary button",
        parentId: "web-actions",
        capabilities: ["contrast", "spacing", "cornerRadius", "typeScale", "focalStrength"],
      },
      {
        id: "web-visual",
        name: "Product field",
        kind: "group",
        purpose: "Contains the drink and flavor shapes",
        role: "product field",
        parentId: "web-hero",
        capabilities: [
          "warmth",
          "contrast",
          "focalStrength",
          "softness",
          "accentStrength",
          "saturation",
        ],
      },
      {
        id: "web-image",
        name: "Signature drink",
        kind: "image",
        purpose: "The hero product photograph",
        role: "product image",
        parentId: "web-visual",
        capabilities: ["warmth", "contrast", "focalStrength", "softness", "saturation", "cropScale"],
      },
      {
        id: "web-color-field",
        name: "Mango field",
        kind: "background",
        purpose: "The flavor color behind the drink",
        role: "color field",
        parentId: "web-visual",
        capabilities: ["warmth", "contrast", "softness", "accentStrength", "saturation"],
      },
      {
        id: "web-sun",
        name: "Cream halo",
        kind: "shape",
        purpose: "Separates and spotlights the drink",
        role: "halo shape",
        parentId: "web-visual",
        capabilities: ["contrast", "focalStrength", "softness", "accentStrength"],
      },
      {
        id: "web-pearls",
        name: "Pearl cluster",
        kind: "decoration",
        purpose: "Carries the Bobalicious pearl motif",
        role: "brand decoration",
        parentId: "web-visual",
        capabilities: ["contrast", "spacing", "focalStrength", "accentStrength"],
      },
      {
        id: "web-footer",
        name: "Footer notes",
        kind: "group",
        purpose: "Location and flavor context",
        role: "footer",
        parentId: "web-frame",
        capabilities: ["contrast", "spacing", "typeScale"],
      },
      {
        id: "web-footer-location",
        name: "Location note",
        kind: "text",
        purpose: "Names the launch market",
        role: "footer label",
        parentId: "web-footer",
        capabilities: ["contrast", "typeScale", "spacing"],
      },
      {
        id: "web-footer-flavors",
        name: "Flavor list",
        kind: "text",
        purpose: "Names signature flavors",
        role: "footer label",
        parentId: "web-footer",
        capabilities: ["contrast", "typeScale", "spacing"],
      },
      {
        id: "web-footer-wave",
        name: "Matcha wave",
        kind: "shape",
        purpose: "Closes the page with a flavor field",
        role: "background shape",
        parentId: "web-frame",
        capabilities: ["warmth", "contrast", "softness", "accentStrength", "saturation"],
      },
    ],
  },
  {
    id: "artifact-graphic",
    kind: "graphic",
    name: "Social campaign",
    format: "1080 × 1350",
    version: 4,
    values: values({
      warmth: 58,
      contrast: 72,
      spacing: 46,
      focalStrength: 76,
      softness: 62,
      surfaceDepth: 68,
      cornerRadius: 38,
      typeScale: 72,
      accentStrength: 82,
      saturation: 66,
    }),
    nodes: [
      {
        id: "graphic-frame",
        name: "Social frame",
        kind: "composition",
        purpose: "The complete social campaign artboard",
        role: "artboard",
        capabilities: [
          "warmth",
          "contrast",
          "spacing",
          "softness",
          "surfaceDepth",
          "saturation",
        ],
      },
      {
        id: "graphic-wash",
        name: "Flavor color wash",
        kind: "background",
        purpose: "Builds the mango, matcha, and coral field",
        role: "background field",
        parentId: "graphic-frame",
        capabilities: ["warmth", "contrast", "softness", "saturation", "accentStrength"],
      },
      {
        id: "graphic-index",
        name: "Campaign label",
        kind: "text",
        purpose: "Identifies the seasonal Bobalicious drop",
        role: "eyebrow",
        parentId: "graphic-frame",
        capabilities: ["contrast", "spacing", "typeScale", "focalStrength"],
      },
      {
        id: "graphic-copy",
        name: "Campaign copy",
        kind: "group",
        purpose: "Holds the message hierarchy",
        role: "copy group",
        parentId: "graphic-frame",
        capabilities: ["contrast", "focalStrength", "typeScale", "spacing"],
      },
      {
        id: "graphic-kicker",
        name: "Flavor kicker",
        kind: "text",
        purpose: "Introduces the flavor pairing",
        role: "eyebrow",
        parentId: "graphic-copy",
        capabilities: ["contrast", "focalStrength", "typeScale", "spacing"],
      },
      {
        id: "graphic-headline",
        name: "Flavor headline",
        kind: "text",
        purpose: "The dominant campaign message",
        role: "headline",
        parentId: "graphic-copy",
        capabilities: ["contrast", "focalStrength", "typeScale", "spacing"],
      },
      {
        id: "graphic-orbit",
        name: "Product crop",
        kind: "group",
        purpose: "Frames the campaign product image",
        role: "product group",
        parentId: "graphic-frame",
        capabilities: [
          "warmth",
          "contrast",
          "focalStrength",
          "softness",
          "accentStrength",
          "saturation",
        ],
      },
      {
        id: "graphic-image",
        name: "Signature drink",
        kind: "image",
        purpose: "The featured campaign product",
        role: "product image",
        parentId: "graphic-orbit",
        capabilities: ["warmth", "contrast", "focalStrength", "softness", "saturation", "cropScale"],
      },
      {
        id: "graphic-footer",
        name: "Campaign footer",
        kind: "group",
        purpose: "Balances flavor and availability notes",
        role: "footer",
        parentId: "graphic-frame",
        capabilities: ["contrast", "spacing", "typeScale"],
      },
      {
        id: "graphic-footer-flavor",
        name: "Flavor note",
        kind: "text",
        purpose: "Describes the flavor pairing",
        role: "caption",
        parentId: "graphic-footer",
        capabilities: ["contrast", "spacing", "typeScale"],
      },
      {
        id: "graphic-footer-availability",
        name: "Availability note",
        kind: "text",
        purpose: "Communicates launch availability",
        role: "caption",
        parentId: "graphic-footer",
        capabilities: ["contrast", "spacing", "typeScale"],
      },
    ],
  },
  {
    id: "artifact-photo",
    kind: "photo",
    name: "Editorial image",
    format: "Photo treatment",
    version: 3,
    values: values({
      warmth: 56,
      contrast: 58,
      spacing: 50,
      focalStrength: 70,
      softness: 42,
      surfaceDepth: 64,
      cornerRadius: 44,
      typeScale: 50,
      accentStrength: 64,
      saturation: 74,
      cropScale: 54,
    }),
    nodes: [
      {
        id: "photo-frame",
        name: "Editorial frame",
        kind: "composition",
        purpose: "The complete editorial treatment",
        role: "photo canvas",
        capabilities: [
          "warmth",
          "contrast",
          "softness",
          "saturation",
          "cropScale",
        ],
      },
      {
        id: "photo-image",
        name: "Milk tea photograph",
        kind: "image",
        purpose: "The base product photograph",
        role: "base image",
        parentId: "photo-frame",
        capabilities: ["warmth", "contrast", "softness", "saturation", "cropScale", "focalStrength"],
      },
      {
        id: "photo-vignette",
        name: "Edge vignette",
        kind: "effect",
        purpose: "Keeps attention on the drink",
        role: "tonal effect",
        parentId: "photo-frame",
        capabilities: ["contrast", "softness", "surfaceDepth", "focalStrength"],
      },
      {
        id: "photo-subject",
        name: "Brown sugar boba",
        kind: "image",
        purpose: "The protected primary product subject",
        role: "subject mask",
        parentId: "photo-frame",
        capabilities: ["contrast", "focalStrength", "softness", "saturation"],
      },
      {
        id: "photo-background",
        name: "Milk tea field",
        kind: "background",
        purpose: "The supporting photographic field",
        role: "background mask",
        parentId: "photo-frame",
        capabilities: ["warmth", "contrast", "softness", "saturation"],
      },
      {
        id: "photo-caption",
        name: "Editorial caption",
        kind: "group",
        purpose: "Labels and credits the photograph",
        role: "caption group",
        parentId: "photo-frame",
        capabilities: ["contrast", "spacing", "typeScale"],
      },
      {
        id: "photo-caption-label",
        name: "Editorial label",
        kind: "text",
        purpose: "Identifies the campaign image",
        role: "caption",
        parentId: "photo-caption",
        capabilities: ["contrast", "spacing", "typeScale"],
      },
      {
        id: "photo-attribution",
        name: "Photo credit",
        kind: "text",
        purpose: "Credits the source photograph",
        role: "attribution",
        parentId: "photo-caption",
        capabilities: ["contrast", "spacing", "typeScale"],
      },
    ],
  },
];

seedArtifacts.forEach(assertValidArtifactOntology);

const instrument = (
  id: InstrumentId,
  label: string,
  description: string,
  min = 0,
  max = 100,
): CapabilityManifest["instruments"][number] => ({
  id,
  label,
  description,
  min,
  max,
});

export const capabilityManifests: Record<
  CreativeArtifact["kind"],
  CapabilityManifest
> = {
  web: {
    artifactKind: "web",
    label: "Web composition",
    description: "Layout, type, tokens, hierarchy, and responsive expression.",
    instruments: [
      instrument("spacing", "Breathing room", "Section and element spacing"),
      instrument("typeScale", "Type hierarchy", "Headline-to-body scale"),
      instrument("focalStrength", "Primary focus", "Visual and action salience"),
      instrument("cornerRadius", "Surface softness", "Component corner language"),
      instrument("warmth", "Palette warmth", "Warm-to-cool surface balance"),
      instrument("contrast", "Contrast", "Separation and legibility"),
      instrument("accentStrength", "Accent color", "Strength of this layer's brand color"),
      instrument("saturation", "Color intensity", "Muted-to-vivid color"),
      instrument("softness", "Edge softness", "Crisp-to-diffused rendering"),
      instrument("surfaceDepth", "Surface depth", "Elevation and layering"),
      instrument("cropScale", "Crop", "Subject scale inside an image layer"),
    ],
  },
  graphic: {
    artifactKind: "graphic",
    label: "Graphic composition",
    description: "Layers, hierarchy, negative space, type, and color rhythm.",
    instruments: [
      instrument("focalStrength", "Visual hierarchy", "Dominance of the primary idea"),
      instrument("typeScale", "Headline scale", "Message scale and weight"),
      instrument("spacing", "Negative space", "Density around key layers"),
      instrument("contrast", "Contrast", "Separation between layers"),
      instrument("warmth", "Temperature", "Warm-to-cool balance"),
      instrument("saturation", "Saturation", "Color intensity"),
      instrument("softness", "Edge softness", "Atmosphere and diffusion"),
      instrument("accentStrength", "Flavor accent", "Strength of the Bobalicious flavor color"),
      instrument("surfaceDepth", "Surface depth", "Elevation and layering"),
      instrument("cropScale", "Crop", "Subject scale inside an image layer"),
    ],
  },
  photo: {
    artifactKind: "photo",
    label: "Photo treatment",
    description: "Crop, light, color, focus, and subject separation.",
    instruments: [
      instrument("warmth", "Temperature", "Warm-to-cool light"),
      instrument("contrast", "Contrast", "Tonal separation"),
      instrument("saturation", "Saturation", "Color intensity"),
      instrument("focalStrength", "Subject focus", "Subject-to-field hierarchy"),
      instrument("softness", "Atmosphere", "Diffusion and softness"),
      instrument("surfaceDepth", "Effect depth", "Strength and reach of tonal effects"),
      instrument("spacing", "Caption spacing", "Distance between caption elements"),
      instrument("typeScale", "Caption size", "Scale of editorial labels and credits"),
      instrument("cropScale", "Crop", "Subject scale inside the frame"),
    ],
  },
};

export const seedProject: StudioProject = {
  id: "project-bobalicious-launch",
  name: "Bobalicious launch",
  brief: "A joyful cross-medium launch for Bobalicious, a premium neighborhood boba shop.",
  accentRule: "Preserve mango, coral, matcha, milk-tea cream, and espresso brown as the Bobalicious brand system.",
  composition: createSeedComposition(),
  compositionReceipts: [],
  designIntelligence: {
    version: "2026.08-design-graph-1",
    brandGrammar: {
      characterHypothesis:
        "Buoyant, layered, tactile, and optimistic; energetic without becoming juvenile.",
      primitives: [
        "Pearl circles and clustered rhythms",
        "Translucent overlaps",
        "Oversized fruit and product crops",
        "Creamy negative space",
        "Rounded, confident typography",
      ],
      invariants: [
        "The drink remains appetizing and materially believable",
        "Primary and supporting copy remain legible",
        "Bobalicious remains visually distinct from the Meant working surface",
      ],
      ranges: [
        "Pearl clusters may move from sparse to dense",
        "Flavor color may dominate within the established palette",
        "Photography may range from clean product focus to restrained collage",
      ],
      forbidden: [
        "Generic neon-gradient technology imagery",
        "Over-glossy plastic rendering",
        "Muddy multicolor overlays",
        "Bobalicious motifs inside GHOSA interface chrome",
      ],
      signatureBehaviors: [
        "Pearls gather and separate to reveal hierarchy",
        "Flavor fields move with soft, buoyant continuity",
      ],
    },
    tasteProfile: {
      preferences: [
        "Expansive, canvas-first composition",
        "Contextual controls that appear only when the selected layer supports them",
        "Review-sheet clarity during judgment",
        "Readable typography and restrained explanatory copy",
      ],
      protectedQualities: [
        "Warmth",
        "Character",
        "Clear distinction between shell and client work",
      ],
      rejectedPatterns: [
        "Tiny descriptive text",
        "Containerized canvas layouts",
        "Generic pink-purple SaaS styling",
        "Persistent panels that crowd the work",
      ],
    },
    semanticOntology: {
      principles: [
        "Every visible, meaningful object resolves to one semantic node or an intentional editable group",
        "Canvas selection, layer selection, scope, and contextual controls always refer to the same node",
        "Small copy, captions, actions, masks, effects, and brand decorations are first-class design material",
        "Parent groups express composition; child nodes preserve edit locality and precise intent grounding",
        "A control appears only when the selected node declares it and the renderer produces a visible bidirectional result",
      ],
      requiredNodeFields: ["kind", "purpose", "parent", "capabilities", "editable fields", "visibility"],
      selectionRules: [
        "Prefer the most specific visible node under the pointer",
        "Never silently route an unmapped child to a misleading hero or frame target",
        "Keep the selected node inside the safe viewport when a floating panel opens",
        "Closing a panel preserves canvas position and world coordinates",
        "Control labels, endpoints, and units describe the visible property rather than an implementation detail",
      ],
      primitiveFamilies: [
        { kind: "composition", firstClassControls: ["palette", "layout spacing", "type scale", "depth", "corners", "crop"] },
        { kind: "text", firstClassControls: ["content", "size", "fill", "alignment", "spacing", "prominence"] },
        { kind: "action", firstClassControls: ["label", "fill", "text size", "corners", "padding", "prominence"] },
        { kind: "image", firstClassControls: ["crop", "scale", "temperature", "contrast", "saturation", "blur"] },
        { kind: "shape", firstClassControls: ["fill", "contrast", "blur", "prominence", "color intensity"] },
        { kind: "group", firstClassControls: ["direction where supported", "alignment where supported", "gap", "inherited hierarchy"] },
        { kind: "background", firstClassControls: ["fill where applicable", "temperature", "contrast", "saturation", "blur"] },
        { kind: "effect", firstClassControls: ["contrast", "blur", "depth", "focus"] },
        { kind: "decoration", firstClassControls: ["fill", "spread", "prominence", "contrast"] },
      ],
    },
    craftSkillLibrary: [
      {
        id: "composition-hierarchy",
        label: "Composition & hierarchy",
        useWhen: "The request changes emphasis, density, scan order, balance, or the relationship between major regions.",
        checks: [
          "The intended first, second, and third reads are unambiguous",
          "The composition still works at its real output size",
          "No decorative treatment is compensating for weak structure",
        ],
      },
      {
        id: "typography-legibility",
        label: "Typography & legibility",
        useWhen: "The request concerns confidence, clarity, readability, editorial rhythm, or information density.",
        checks: [
          "Body and supporting text meet the readable type floor",
          "Heading and body roles remain visibly distinct",
          "Line length, wrapping, and numeric alignment suit the medium",
        ],
      },
      {
        id: "interaction-affordance",
        label: "Interaction & affordance",
        useWhen: "The artifact contains controls, navigation, selection, progressive disclosure, or a multi-step task.",
        checks: [
          "Primary action and current state are apparent without explanation",
          "Interactive targets are comfortably reachable and keyboard accessible",
          "Loading, success, failure, and recovery states are accounted for",
        ],
      },
      {
        id: "brand-character",
        label: "Brand character",
        useWhen: "A change could make the work feel generic, erase a signature quality, or cross the boundary between GHOSA and the client brand.",
        checks: [
          "At least one signature primitive remains legible",
          "The change obeys palette, material, voice, and behavior invariants",
          "The result could not be relabeled as a generic SaaS template",
        ],
      },
      {
        id: "motion-choreography",
        label: "Motion choreography",
        useWhen: "State, spatial continuity, sequencing, feedback, or temporal storytelling materially improves understanding.",
        checks: [
          "Every motion has a semantic purpose and named source and destination states",
          "Timing comes from the shared motion vocabulary rather than a one-off duration",
          "A calm reduced-motion equivalent preserves hierarchy and feedback",
        ],
      },
      {
        id: "edit-locality",
        label: "Edit locality",
        useWhen: "The instruction is scoped to a layer, region, property, or bounded reference.",
        checks: [
          "Only the intended targets and capabilities changed",
          "Protected neighboring layers remain stable",
          "References govern only the properties explicitly assigned to them",
        ],
      },
      {
        id: "production-integrity",
        label: "Production integrity",
        useWhen: "The design must remain responsive, editable, reusable, or ready for implementation.",
        checks: [
          "Structured and programmable elements remain semantic and editable",
          "Layout shifts, overflow, contrast, and responsive behavior are verified",
          "Generated raster media is contained within an appropriate editable layer",
        ],
      },
    ],
    contextProfiles: [
      {
        artifactKind: "web",
        objective: "Help someone understand, choose, and act while preserving responsive structure.",
        prioritize: ["Scan order", "Action clarity", "Responsive hierarchy", "Accessible interaction"],
        commonFailures: ["Decorative dashboard chrome", "Weak primary action", "Tiny explanatory copy", "Layout shift"],
      },
      {
        artifactKind: "graphic",
        objective: "Communicate one memorable idea at a glance in a fixed composition.",
        prioritize: ["Immediate focal point", "Silhouette", "Type-image tension", "Output-size legibility"],
        commonFailures: ["Equal visual weight", "Template-like decoration", "Crowded edges", "Copy that only works when zoomed"],
      },
      {
        artifactKind: "photo",
        objective: "Direct attention and mood without losing material believability.",
        prioritize: ["Subject separation", "Light continuity", "Appetite appeal", "Localized treatment"],
        commonFailures: ["Plastic texture", "Muddy overlays", "Global edits for local problems", "Broken light direction"],
      },
    ],
    motionVocabulary: {
      tokens: [
        { id: "snap", purpose: "Pressed states and immediate acknowledgement", timing: "90–140ms; crisp ease-out" },
        { id: "ui", purpose: "Routine interface state changes", timing: "160–240ms; controlled ease-out" },
        { id: "gentle", purpose: "Panels, spatial continuity, and calm reveals", timing: "280–380ms; soft spring" },
        { id: "lively", purpose: "Expressive Bobalicious moments and celebratory feedback", timing: "360–520ms; buoyant spring" },
        { id: "ambient", purpose: "Low-attention environmental movement", timing: "700–1200ms; slow ease-in-out" },
      ],
      stagger: ["tight", "base", "relaxed"],
      reducedMotion: "calm",
    },
    representationPolicy: {
      preferenceOrder: ["structured", "programmable", "generative"],
      rules: [
        "Prefer semantic layers, components, vectors, tokens, and coded graphics when they can express the idea",
        "Treat sketches and reference images as property-scoped design evidence, not permission to flatten or copy an entire artifact",
        "Use generative raster execution only for bounded visual assets, photography, texture, or illustration that benefits from it",
        "Keep generated assets inside replaceable, masked, and provenance-linked layers",
      ],
    },
    acceptanceBar: [
      "A designer should not need to retouch the hierarchy, spacing, or state clarity before review",
      "The result must satisfy the stated intent without violating preserved qualities",
      "The output should feel specific to Bobalicious and the artifact medium, not like generic AI styling",
      "The smallest coherent change should solve the problem; unrelated regions should remain stable",
      "Editable structure, accessibility, and real output-size legibility take priority over decorative novelty",
      "Every exposed control must visibly change the selected semantic layer at both ends of its range",
    ],
    craftRules: [
      "Preserve visible focus and keyboard access",
      "Maintain a comfortable readable type floor",
      "Use color with a non-color status cue",
      "Keep transitions interruptible and provide reduced-motion behavior",
      "Inspect scope locality, overflow, contrast, and brand invariants before approval",
      "Never expose an inert control or route a control to a neighboring layer",
    ],
  },
  artifacts: seedArtifacts,
  expressionPackets: [],
  provenance: [],
};

export const exampleDirections = [
  "Make it feel warmer but not more playful. Keep the layout and brand palette intact.",
  "Make the drink feel more premium, but not luxurious. Keep it friendly and materially believable.",
  "Make the campaign cleaner without making it sparse or sterile.",
];
